Document: logscript
Title: Debian logscript Manual
Author: <insert document author here>
Abstract: This manual describes what logscript is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/logscript/logscript.sgml.gz

Format: postscript
Files: /usr/share/doc/logscript/logscript.ps.gz

Format: text
Files: /usr/share/doc/logscript/logscript.text.gz

Format: HTML
Index: /usr/share/doc/logscript/html/index.html
Files: /usr/share/doc/logscript/html/*.html
